### ISSUE TITLE
install prompt on WSL2 fails

### ISSUE THREAD

**Issue by sjk07** [pulsebridge/uber#78]
seems like there is an issue with the bootstrap.sh -> install.sh variable passing. 
https://github.com/automotiveMastermind/prompt/blob/a95f87e6bdba2404804fb3ba30396805c1b41102/bootstrap.sh#L90

here are two sample files that cause the issue:
bootstrap.sh
```
#!/usr/bin/env sh

set -e

DIR=$(mktemp -d)
. "./test.sh" something "$DIR"
```

install.sh
```
SCRIPT_DIR=${2:-$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)}

echo $SCRIPT_DIR
```

calling sh -x ./bootstrap.sh produces:
```
scott@DESKTOP-AFL3UD5:~$ sh -x ./bootstrap.sh
+ set -e
+ mktemp -d
+ DIR=/tmp/tmp.od69gATykC
+ . ./install.sh something /tmp/tmp.od69gATykC
+ dirname -- ./bootstrap.sh
+ CDPATH= cd -- .
+ pwd -P
+ SCRIPT_DIR=/home/scott
+ echo /home/scott
```

adding the `.` in front of the calling command to ./install.sh seems to cause something funky to happen and the second variable does not propagate . 

removing the `.` in  `. "./test.sh" something "$DIR"` to `"./test.sh" something "$DIR"` results in the correct output:

```
scott@DESKTOP-AFL3UD5:~$ sh -x ./bootstrap.sh
+ set -e
+ mktemp -d
+ DIR=/tmp/tmp.7Sbl0QtwLL
+ ./install.sh something /tmp/tmp.7Sbl0QtwLL
/tmp/tmp.7Sbl0QtwLL
```

PR incoming; want to see if this is the same case in other dists. also wondering why this was not caught in CI

**Comment by patrickserrano** [comment]
I wonder if this is related to the upgrade/install issue I ran into last week using WSL1. I didn't finish debugging but it looked like the value of `$SCRIPTDIR` in `install.sh` wasn't being set correctly which was causing the install to look in `$HOME/templates` instead of `temp_dir/templates`.

**Comment by sjk07** [comment]
@patrickserrano yup that was the exact problem 😄 

PR fixes the issue. dunno if it causes problems for the other OSs

**Comment by dmccaffery** [comment]
I will look at the CI logs, but it definitely seems to work just fine there. :)

**Comment by dmccaffery** [comment]
@sjk07 / @patrickserrano : this was working in ci/cd because we are invoking install.sh directly: https://github.com/automotiveMastermind/prompt/blob/60b9f37f32676dccd01e9e40dc5e8c6bb176fa0d/hack/install.sh#L7 and we're not relying on the temp dir -- basically, the bootstrap script isn't invoked as it would clone the upstream rather than whatever changes are included in the PR (until after its merged).

There is no temp dir in this scenario and thus the default (current script path) is used. There isn't any good way to test the bootstrap script itself while going through the real execution path.
